#eureka的端口号
server:
  port: 3333
eureka:
  instance:
   preferIpAddress : true
   ip-address: 192.168.1.74
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
      defaultZone: http://192.168.1.252:3333/eureka/
spring:
  application:
    name: double-eureka-server