eureka:
  client:
    serviceUrl:
      #      eureka的注册中心地址
      defaultZone: http://192.168.1.74:3333/eureka/,http://192.168.1.252:3333/eureka/
server:
  #  此项目端口号
  port: 8881
spring:
  application:
    #    注册进eureka的名字
    name: order-server